version: "3.2"

services:
  utils_server:
    build:
      context    : ./
      dockerfile : ./sys/server/Dockerfile
      
    volumes:
      - ./:/var/www/
    depends_on:
      - mysql_server
      - apache_server
    container_name:
      utils_server
